services:
  ms-saga:
    image: ms-saga-spring
    container_name: ms-saga
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backend
    ports:
      - "8085:8085"
    environment:
      - SERVER_PORT=8085
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/saga_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgrespass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_USERNAME=rabbit
      - SPRING_RABBITMQ_PASSWORD=rabbitpass
    depends_on:
      - rabbitmq
      - postgres-db
