services:
  api-gateway:
    image: api-gateway-node
    container_name: api-gateway
    build:
      context: .
      dockerfile: api-gateway.Dockerfile
    ports:
      - "80:80"
    environment:
      - PORT=80
      - FRONT=http://localhost:4200
      - AUTH_URI=http://ms-auth:8081
      - GERENTES_URI=http://ms-gerente:8082
      - CLIENTES_URI=http://ms-cliente:8083
      - CONTAS_URI=http://ms-conta:8084
    networks:
      - backend
    depends_on:
      - rabbitmq 
      
networks:
  backend: