services:
  api-gateway:
    image: api-gateway-node
    container_name: api-gateway
    build:
      context: .
      dockerfile: api-gateway.Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - FRONT=http://localhost:8080
      - AUTH_URI=http://ms-auth:8080
      - GERENTES_URI=http://ms-gerente:8082
      - CLIENTES_URI=http://ms-cliente:8086
      - CONTAS_URI=http://ms-conta:8083
      - SAGA_URI=http://ms-saga:8085
      - SECRET=super-secret-key-for-jwt
    networks:
      - backend
    depends_on:
      - rabbitmq 
