spring.application.name=conta-service
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.username=rabbit
spring.rabbitmq.password=rabbitpass

# BANCO DE COMANDO (WRITE) E CONSULTA (READ) - MESMO BANCO POR ENQUANTO
spring.datasource.command.jdbc-url=jdbc:postgresql://localhost:5432/conta_comando
spring.datasource.command.username=postgres
spring.datasource.command.password=root
spring.datasource.command.driver-class-name=org.postgresql.Driver
spring.jpa.command.hibernate.ddl-auto=update
spring.jpa.command.show-sql=false

spring.datasource.query.jdbc-url=jdbc:postgresql://localhost:5432/conta_consulta
spring.datasource.query.username=postgres
spring.datasource.query.password=root
spring.datasource.query.driver-class-name=org.postgresql.Driver
spring.jpa.query.hibernate.ddl-auto=update
spring.jpa.query.show-sql=false