spring.application.name=conta-service

# BANCO DE LEITURA
spring.datasource.command.jdbc-url=jdbc:postgresql://localhost:5432/conta_comando
spring.datasource.command.username=postgres
spring.datasource.command.password=postgres
spring.datasource.command.driver-class-name=org.postgresql.Driver
spring.jpa.command.hibernate.ddl-auto=update


# BANCO DE CONSULTA 
spring.datasource.query.jdbc-url=jdbc:postgresql://localhost:5432/conta_consulta
spring.datasource.query.username=postgres
spring.datasource.query.password=postgres
spring.datasource.query.driver-class-name=org.postgresql.Driver
spring.jpa.query.hibernate.ddl-auto=update