# ===== RabbitMQ
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    volumes:
    networks: backend
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabbitpass