spring.application.name=saga

# Porta da aplicação
server.port=${SERVER_PORT:8085}

# ==========================================
# Configurações do Banco de Dados PostgreSQL
# ==========================================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/saga_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do JPA/Hibernate
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ==========================================
# Configurações do RabbitMQ
# ==========================================
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:rabbit}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:rabbitpass}
