# ===== Microsserviço de autenticação
  ms-auth:
    image: ms-auth-spring
    container_name: ms-auth
    build: ./MS-Auth/ms-auth.Dockerfile
    networks: backend
    depends_on:
      rabbitmq:
      ms-auth-db:

# ===== BD (Mongo)
  ms-auth-db:
    image: mongodb/mongodb-community-server:latest
    container_name: ms-auth-db
    environment:
    #  - usuário
    #  - senha
    # E outras variáveis relevantes
    volumes:
    #  - dados:/dados
    networks: backend