services:
  ms-gerente:
    image: ms-gerente-spring
    container_name: ms-gerente
    build:
      context: .
      dockerfile: ms-gerente.Dockerfile
    networks:
      - backend
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/gerente_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgrespass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_USERNAME=rabbit
      - SPRING_RABBITMQ_PASSWORD=rabbitpass
    depends_on:
      - rabbitmq
      - postgres-db