services:
  ms-gerente:
    image: ms-gerente-spring
    container_name: ms-gerente
    build:
      context: .
      dockerfile: ms-gerente.Dockerfile
    networks:
      - backend
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ms-gerente-db:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASS}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - ms-gerente-db

  # BD (Postgres)
  ms-gerente-db:
    image: postgres:15-alpine
    container_name: ms-gerente-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT_LOCAL}:5432"
    volumes:
      - ms_gerente_dados:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  ms_gerente_dados:
