services:
  ms-auth:
    image: ms-auth-spring
    container_name: ms-auth
    build: 
      context: ./
      dockerfile: ms-auth.Dockerfile
    networks:
      - backend
    depends_on:
      - rabbitmq
      - ms-auth-db
    environment:
      - SPRING_MONGODB_HOST=ms-auth-db
      - SPRING_MONGODB_PORT=27017
      - SPRING_MONGODB_DATABASE=auth

  ms-auth-db:
    image: mongodb/mongodb-community-server:latest
    container_name: ms-auth-db
    networks:
      - backend
    volumes:
      - ms_auth_db_data:/data/db

volumes:
  ms_auth_db_data:
