spring.application.name=cliente
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.username=rabbit
spring.rabbitmq.password=rabbitpass

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
