server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: auth_route
            uri: ${AUTH_URI:http://localhost:8081} // varíaveis de ambiente passadas pelo docker + fallback
            predicates:
              - Path=/login
              
          - id: gerentes_route
            uri: ${GERENTES_URI:http://localhost:8082}
            predicates:
              - Path=/gerentes/**
              
          - id: clientes_route
            uri: ${CLIENTES_URI:http://localhost:8083}
            predicates:
              - Path=/clientes/**
              
          - id: contas_route
            uri: ${CONTAS_URI:http://localhost:8084}
            predicates:
              - Path=/contas/**
