spring.application.name=auth_service
spring.data.mongodb.host=${SPRING_MONGODB_HOST:localhost}
spring.data.mongodb.port=${SPRING_MONGODB_PORT:27017}
spring.data.mongodb.database=${SPRING_MONGODB_DATABASE:auth}

spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:rabbit}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:rabbitpass}

#spring.rabbitmq.host=rabbitmq
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=rabbit
#spring.rabbitmq.password=rabbitpass